version: '3'

services:

  flask:
    container_name: flask
    build: 
      context: .
      dockerfile: ./flask/Dockerfile
    restart: always
    privileged: true
    volumes:
    - ./:/usr/src/app/
    environment:
      TZ: Asia/Tokyo
    command: uwsgi --ini /usr/src/app/uwsgi.ini

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    volumes:
    - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "9999:9999"
    environment:
      TZ: Asia/Tokyo
